<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesMoviesProfileProxy extends \Entities\MoviesProfile implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setDirector($director)
    {
        $this->__load();
        return parent::setDirector($director);
    }

    public function getDirector()
    {
        $this->__load();
        return parent::getDirector();
    }

    public function setProducer($producer)
    {
        $this->__load();
        return parent::setProducer($producer);
    }

    public function getProducer()
    {
        $this->__load();
        return parent::getProducer();
    }

    public function setActors($actors)
    {
        $this->__load();
        return parent::setActors($actors);
    }

    public function getActors()
    {
        $this->__load();
        return parent::getActors();
    }

    public function setReleaseDate($releaseDate)
    {
        $this->__load();
        return parent::setReleaseDate($releaseDate);
    }

    public function getReleaseDate()
    {
        $this->__load();
        return parent::getReleaseDate();
    }

    public function setSummary($summary)
    {
        $this->__load();
        return parent::setSummary($summary);
    }

    public function getSummary()
    {
        $this->__load();
        return parent::getSummary();
    }

    public function addGenres(\Entities\Genres $genres)
    {
        $this->__load();
        return parent::addGenres($genres);
    }

    public function getGenres()
    {
        $this->__load();
        return parent::getGenres();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'director', 'producer', 'actors', 'releaseDate', 'summary', 'genres');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}